import { AutoCodeController } from '@/modules/tool/auto-code/auto-code.controller';
import { AutoCodeService } from '@/modules/tool/auto-code/auto-code.service';
import { Module } from '@nestjs/common';

@Module({
  imports: [],
  controllers: [AutoCodeController],
  providers: [AutoCodeService],
})
export class AutoCodeModule {
  constructor() {
    const options = {
      createBy: 'nva',
      name: 'dept',
      nameZh: '部门',
      modelName: 'Dept',
      webPath: 'aaa/dept',
      tempId: '556fb3aa57c4460692e07fd215fa9bb6',
      routePath: 'aaa/dept',
      dictKeys: ['enableStatus'],
      fields: [
        {
          nameCh: 'id',
          name: 'id',
          nameJson: 'id',
          dataName: 'id',
          type: 'String',
          tsType: 'string',
          isRequired: false,
          isSearch: false,
          isPrimary: true,
          isTranslate: false,
          isAutoIncrement: false,
          isAdd: false,
          isShowTable: false,
          isUnique: false,
          defaultValue: '',
          size: 36,
          formItemType: 'input',
          dictCode: '',
        },
        {
          nameCh: '部门名称',
          name: 'deptName',
          nameJson: 'deptName',
          dataName: 'dept_name',
          type: 'String',
          tsType: 'string',
          isRequired: true,
          isSearch: true,
          isPrimary: false,
          isTranslate: false,
          isAutoIncrement: false,
          isAdd: true,
          isShowTable: true,
          isUnique: true,
          searchType: 'LIKE',
          defaultValue: '',
          size: 30,
          formItemType: 'input',
          dictCode: '',
          decimal: {},
        },
        {
          nameCh: '创建人',
          name: 'createBy',
          nameJson: 'createBy',
          dataName: 'create_by',
          type: 'String',
          tsType: 'string',
          isRequired: false,
          isSearch: false,
          isPrimary: false,
          isTranslate: false,
          isAutoIncrement: false,
          isAdd: false,
          isShowTable: true,
          isUnique: false,
          defaultValue: '',
          size: 30,
          formItemType: 'input',
          dictCode: '',
        },
        {
          nameCh: '创建时间',
          name: 'createTime',
          nameJson: 'createTime',
          dataName: 'create_time',
          type: 'DateTime',
          tsType: 'string',
          isRequired: false,
          isSearch: false,
          isPrimary: false,
          isTranslate: true,
          isAutoIncrement: false,
          isAdd: false,
          isShowTable: true,
          isUnique: false,
          defaultValue: '',
          size: 0,
          formItemType: 'datetime',
          dictCode: '',
        },
        {
          nameCh: '修改人',
          name: 'updateBy',
          nameJson: 'updateBy',
          dataName: 'update_by',
          type: 'String',
          tsType: 'string',
          isRequired: false,
          isSearch: false,
          isPrimary: false,
          isTranslate: false,
          isAutoIncrement: false,
          isAdd: false,
          isShowTable: false,
          isUnique: false,
          defaultValue: '',
          size: 30,
          formItemType: 'input',
          dictCode: '',
        },
        {
          nameCh: '修改时间',
          name: 'updateTime',
          nameJson: 'updateTime',
          dataName: 'update_time',
          type: 'DateTime',
          tsType: 'string',
          isRequired: false,
          isSearch: false,
          isPrimary: false,
          isTranslate: true,
          isAutoIncrement: false,
          isAdd: false,
          isShowTable: false,
          isUnique: false,
          defaultValue: '',
          size: 0,
          formItemType: 'datetime',
          dictCode: '',
        },
      ],
      serverPath: 'modules/aaa',
      camelCase: 'dept',
      pascalCase: 'Dept',
      snakeCase: 'dept',
      pimaryKeyType: 'string',
      primaryKeyIsNumber: false,
      authPrefix: 'aaa:dept',
      primaryKey: 'id',
      serverDir:
        'F:\\git\\nest-vue-admin\\apps\\server\\src\\modules\\aaa\\dept',
      genServerFilePaths: [
        'F:\\git\\nest-vue-admin\\apps\\server\\src\\modules\\aaa\\dept\\dept.controller.ts',
        'F:\\git\\nest-vue-admin\\apps\\server\\src\\modules\\aaa\\dept\\dept.service.ts',
        'F:\\git\\nest-vue-admin\\apps\\server\\src\\modules\\aaa\\dept\\dto\\req-dept.dto.ts',
        'F:\\git\\nest-vue-admin\\apps\\server\\src\\modules\\aaa\\dept\\dto\\res-dept.dto.ts',
        'F:\\git\\nest-vue-admin\\apps\\server\\src\\modules\\aaa\\dept\\dept.module.ts',
      ],
      genWebFilePaths: [
        'F:\\git\\nest-vue-admin\\apps\\web\\src\\views\\aaa\\dept\\dept\\index.vue',
        'F:\\git\\nest-vue-admin\\apps\\web\\src\\api\\aaa\\dept\\dept.js',
      ],
    };
    // createWebTempNew(options as any);
  }
}
