import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcryptjs';
import { deptIds } from './sys-dept';
import { postIds } from './sys-post';

import { generateUUid } from '../index';

const password = '$2b$10$KTXfR37g00JCSvByd89Cx.zoUn4.vsICmMWWgUh26Qzscx4F4sCnG'; // 123456

const users = [
  // 超级管理员
  {
    id: '1',
    userName: 'admin',
    nickName: '超级管理员',
    password,
    avatar: null,
    email: 'admin@example.com',
    phone: '13800138000',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.hq,
    postId: postIds.ceo,
    remark: '系统超级管理员',
  },

  // 技术中心
  {
    id: '2',
    userName: 'zhangwei',
    nickName: '张伟',
    password,
    avatar: null,
    email: 'zhangwei@example.com',
    phone: '13900001111',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.techCenter,
    postId: postIds.cto,
    remark: '技术总监',
  },
  {
    id: '3',
    userName: 'liming',
    nickName: '李明',
    password,
    avatar: null,
    email: 'liming@example.com',
    phone: '13900002222',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.techCenter,
    postId: postIds.techManager,
    remark: '技术经理',
  },

  // 前端组
  {
    id: '4',
    userName: 'wangfang',
    nickName: '王芳',
    password,
    avatar: null,
    email: 'wangfang@example.com',
    phone: '13900003333',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.frontend,
    postId: postIds.feLead,
    remark: '前端组长',
  },
  {
    id: '5',
    userName: 'liuyang',
    nickName: '刘洋',
    password,
    avatar: null,
    email: 'liuyang@example.com',
    phone: '13900004444',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.frontend,
    postId: postIds.feSenior,
    remark: '高级前端工程师',
  },
  {
    id: '6',
    userName: 'chenxin',
    nickName: '陈欣',
    password,
    avatar: null,
    email: 'chenxin@example.com',
    phone: '13900005555',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.frontend,
    postId: postIds.feEngineer,
    remark: '前端工程师',
  },
  {
    id: '7',
    userName: 'zhaolei',
    nickName: '赵磊',
    password,
    avatar: null,
    email: 'zhaolei@example.com',
    phone: '13900006666',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.frontend,
    postId: postIds.feEngineer,
    remark: '前端工程师',
  },

  // 后端组
  {
    id: '8',
    userName: 'sunqiang',
    nickName: '孙强',
    password,
    avatar: null,
    email: 'sunqiang@example.com',
    phone: '13900007777',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.backend,
    postId: postIds.beLead,
    remark: '后端组长',
  },
  {
    id: '9',
    userName: 'zhoujie',
    nickName: '周杰',
    password,
    avatar: null,
    email: 'zhoujie@example.com',
    phone: '13900008888',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.backend,
    postId: postIds.beSenior,
    remark: '高级后端工程师',
  },
  {
    id: '10',
    userName: 'wuli',
    nickName: '吴丽',
    password,
    avatar: null,
    email: 'wuli@example.com',
    phone: '13900009999',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.backend,
    postId: postIds.beEngineer,
    remark: '后端工程师',
  },

  // 测试组
  {
    id: '11',
    userName: 'zhenghua',
    nickName: '郑华',
    password,
    avatar: null,
    email: 'zhenghua@example.com',
    phone: '13900010101',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.qa,
    postId: postIds.qaLead,
    remark: '测试组长',
  },
  {
    id: '12',
    userName: 'huangying',
    nickName: '黄英',
    password,
    avatar: null,
    email: 'huangying@example.com',
    phone: '13900010202',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.qa,
    postId: postIds.qaEngineer,
    remark: '测试工程师',
  },

  // 运维组
  {
    id: '13',
    userName: 'xujun',
    nickName: '徐军',
    password,
    avatar: null,
    email: 'xujun@example.com',
    phone: '13900010303',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.devops,
    postId: postIds.devopsLead,
    remark: '运维组长',
  },
  {
    id: '14',
    userName: 'heping',
    nickName: '何平',
    password,
    avatar: null,
    email: 'heping@example.com',
    phone: '13900010404',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.devops,
    postId: postIds.devopsEngineer,
    remark: '运维工程师',
  },

  // 产品中心
  {
    id: '15',
    userName: 'yanglin',
    nickName: '杨林',
    password,
    avatar: null,
    email: 'yanglin@example.com',
    phone: '13900010505',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.productCenter,
    postId: postIds.productDirector,
    remark: '产品总监',
  },
  {
    id: '16',
    userName: 'malin',
    nickName: '马林',
    password,
    avatar: null,
    email: 'malin@example.com',
    phone: '13900010606',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.productCenter,
    postId: postIds.productManager,
    remark: '产品经理',
  },

  // 用户体验组
  {
    id: '17',
    userName: 'fengna',
    nickName: '冯娜',
    password,
    avatar: null,
    email: 'fengna@example.com',
    phone: '13900010707',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.ux,
    postId: postIds.uxLead,
    remark: 'UX组长',
  },
  {
    id: '18',
    userName: 'luowen',
    nickName: '罗雯',
    password,
    avatar: null,
    email: 'luowen@example.com',
    phone: '13900010808',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.ux,
    postId: postIds.uiDesigner,
    remark: 'UI设计师',
  },

  // 运营中心
  {
    id: '19',
    userName: 'tanghao',
    nickName: '唐浩',
    password,
    avatar: null,
    email: 'tanghao@example.com',
    phone: '13900010909',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.operationCenter,
    postId: postIds.operationDirector,
    remark: '运营总监',
  },

  // 市场推广组
  {
    id: '20',
    userName: 'dengwei',
    nickName: '邓伟',
    password,
    avatar: null,
    email: 'dengwei@example.com',
    phone: '13900011010',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.marketing,
    postId: postIds.marketingLead,
    remark: '市场负责人',
  },
  {
    id: '21',
    userName: 'caofei',
    nickName: '曹飞',
    password,
    avatar: null,
    email: 'caofei@example.com',
    phone: '13900011111',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.marketing,
    postId: postIds.marketingStaff,
    remark: '市场专员',
  },

  // 客户服务组
  {
    id: '22',
    userName: 'pengli',
    nickName: '彭丽',
    password,
    avatar: null,
    email: 'pengli@example.com',
    phone: '13900011212',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.customerService,
    postId: postIds.csLead,
    remark: '客服主管',
  },
  {
    id: '23',
    userName: 'xiejuan',
    nickName: '谢娟',
    password,
    avatar: null,
    email: 'xiejuan@example.com',
    phone: '13900011313',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.customerService,
    postId: postIds.csStaff,
    remark: '客服专员',
  },

  // 人力资源部
  {
    id: '24',
    userName: 'jiangnan',
    nickName: '江南',
    password,
    avatar: null,
    email: 'jiangnan@example.com',
    phone: '13900011414',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.hr,
    postId: postIds.hrDirector,
    remark: 'HR总监',
  },
  {
    id: '25',
    userName: 'hanxue',
    nickName: '韩雪',
    password,
    avatar: null,
    email: 'hanxue@example.com',
    phone: '13900011515',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.hr,
    postId: postIds.hrManager,
    remark: 'HR经理',
  },
  {
    id: '26',
    userName: 'tianyu',
    nickName: '田宇',
    password,
    avatar: null,
    email: 'tianyu@example.com',
    phone: '13900011616',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.hr,
    postId: postIds.recruiter,
    remark: '招聘专员',
  },

  // 财务部
  {
    id: '27',
    userName: 'shenqian',
    nickName: '沈倩',
    password,
    avatar: null,
    email: 'shenqian@example.com',
    phone: '13900011717',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.finance,
    postId: postIds.financeDirector,
    remark: '财务总监',
  },
  {
    id: '28',
    userName: 'yuanfang',
    nickName: '袁芳',
    password,
    avatar: null,
    email: 'yuanfang@example.com',
    phone: '13900011818',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.finance,
    postId: postIds.accountant,
    remark: '会计',
  },
  {
    id: '29',
    userName: 'luhao',
    nickName: '陆浩',
    password,
    avatar: null,
    email: 'luhao@example.com',
    phone: '13900011919',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.finance,
    postId: postIds.cashier,
    remark: '出纳',
  },

  // 实习生
  {
    id: '30',
    userName: 'intern01',
    nickName: '实习生小明',
    password,
    avatar: null,
    email: 'intern01@example.com',
    phone: '13900012020',
    sex: '0',
    status: '0',
    userType: '00',
    deptId: deptIds.frontend,
    postId: postIds.intern,
    remark: '前端实习生',
  },
  {
    id: '31',
    userName: 'intern02',
    nickName: '实习生小红',
    password,
    avatar: null,
    email: 'intern02@example.com',
    phone: '13900012121',
    sex: '1',
    status: '0',
    userType: '00',
    deptId: deptIds.backend,
    postId: postIds.intern,
    remark: '后端实习生',
  },

  // 停用账号（测试用）
  {
    id: '32',
    userName: 'disabled01',
    nickName: '已停用用户',
    password,
    avatar: null,
    email: 'disabled01@example.com',
    phone: '13900012222',
    sex: '0',
    status: '1',
    userType: '00',
    deptId: deptIds.techCenter,
    postId: postIds.feEngineer,
    remark: '测试停用状态',
  },
];

export async function initUser(prisma: PrismaClient) {
  console.log('开始初始化用户...');
  for (const user of users) {
    await prisma.sysUser.upsert({
      where: { userName: user.userName },
      update: {
        nickName: user.nickName,
        email: user.email,
        phone: user.phone,
        sex: user.sex,
        status: user.status,
        userType: user.userType,
        deptId: user.deptId,
        postId: user.postId,
        remark: user.remark,
      },
      create: user,
    });
  }

  // 将 admin 用户绑定到超级管理员角色
  const superRole = await prisma.sysRole.findUnique({
    where: { key: 'super_admin' },
  });
  if (superRole) {
    await prisma.sysUser.update({
      where: { userName: 'admin' },
      data: {
        roles: {
          set: [{ id: superRole.id }],
        },
      },
    });
  }

  console.log('用户数据初始化完成');
}
